#! /usr/bin/env bash
set -Eeuox pipefail
RUN_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
DATA_DIR="/var/opt/mastr-export"
mkdir -p "${DATA_DIR}"

# Clean up, keeping 3 most recent copies
find "${DATA_DIR}" -maxdepth 1 -type d -regex '.*/[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]' |
  sort --reverse |
  tail --lines=+4 |
  xargs rm -rf
