#! /usr/bin/env bash
set -Eeuox pipefail
RUN_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
DATA_DIR="/var/opt/mastr-export"
mkdir -p "${DATA_DIR}"

# Wait until the next hour has passed, with 60s jitter
snooze -H'*' -J60

# Setup
function mastr() {
    pipx run --spec='git+https://github.com/curiousleo/mastr-export@main' cli "$@"
}

# Check if there is a newer version of the export
LATEST_URL="$(mastr print-export-url)"
LATEST_DATE="$(printf '%s\n' "${LATEST_URL}" | sed 's/^.*_\([0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]\)_.*$/\1/')"
LATEST_DIR="${DATA_DIR}/${LATEST_DATE}"
ZIP="${LATEST_DIR}/export.xml.zip"
DUCKDB="${LATEST_DIR}/export.duckdb1"

# Download file if missing
if ! [[ -f "${ZIP}" ]]; then
    mkdir -p "${LATEST_DIR}"
    axel --quiet --output="${ZIP}" "${LATEST_URL}"
fi

# Extract DuckDB if missing, and restart trinoli
if ! [[ -f "${DUCKDB}" ]]; then
    rm -f "${DUCKDB}.tmp"
    mastr extract-to-duckdb --export "${ZIP}" --duckdb "${DUCKDB}.tmp"
    mv "${DUCKDB}.tmp" "${DUCKDB}"

    # Restart trinoli
    TRINOLI_SVC_DIR="${RUN_DIR}/../trinoli"
    echo "${DUCKDB}" >"${TRINOLI_SVC_DIR}/duckdb-file"
    s6-svc -r "${TRINOLI_SVC_DIR}"
fi
