#! /usr/bin/env bash
set -Eeuox pipefail
RUN_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
DATA_DIR="/var/opt/mastr-export"
mkdir -p "${DATA_DIR}"

# Wait until the next hour has passed, with 60s jitter
snooze -H'*' -J60

# Setup
function mastr() {
    pipx run --spec='git+https://github.com/curiousleo/mastr-export@main' cli "$@"
}

# Get latest URL
LATEST_URL="$(mastr print-export-url)"
LATEST_DATE="$(printf '%s\n' "${LATEST_URL}" | sed 's/^.*_\([0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]\)_.*$/\1/')"
LATEST_DIR="${DATA_DIR}/${LATEST_DATE}"

# Exit if DuckDB file already exists
ZIP="${LATEST_DIR}/export.xml.zip"
DUCKDB="${LATEST_DIR}/export.duckdb1"
if [[ -f "${DUCKDB}" ]]; then
    exit 0
fi

# Download export file if missing
if ! [[ -f "${ZIP}" ]]; then
    mkdir -p "${LATEST_DIR}"
    axel --quiet --output="${ZIP}" "${LATEST_URL}"
fi

# Extract to DuckDB
rm -f "${DUCKDB}.tmp"
mastr extract-to-duckdb --export "${ZIP}" --duckdb "${DUCKDB}.tmp"
mv "${DUCKDB}.tmp" "${DUCKDB}"

# Restart trinoli
TRINOLI_SVC_DIR="${RUN_DIR}/../trinoli"
echo "${DUCKDB}" >"${TRINOLI_SVC_DIR}/duckdb-file"
s6-svc -r "${TRINOLI_SVC_DIR}"
