#! /usr/bin/env bash
set -Eeuox pipefail
RUN_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

# Wait until the next hour has passed, with 60s jitter
snooze -H'*' -J60

# Setup
function mastr() {
    pipx run --spec='git+https://github.com/curiousleo/mastr-export@main' cli "$@"
}
EXPORT='bnetza_mastr.xml.zip'
DUCKDB='bnetza_mastr.duckdb1'

# Check if there is a newer version of the export
LATEST_URL="$(mastr print-export-url)"
LATEST_URL_FILE="${RUN_DIR}/latest-url"
if [[ -f "${LATEST_URL_FILE}" && "<(${LATEST_URL_FILE})" = "${LATEST_URL}" ]]; then
    # Nothing to do
    exit 0
fi

# Download and extract the new export
axel --quiet --output="${EXPORT}" "$(mastr print-export-url)"
mastr extract-to-duckdb --export "${EXPORT}" --duckdb "${DUCKDB}"

# Restart trinoli
TRINOLI_SVC_DIR="${RUN_DIR}/../trinoli"
echo "${DUCKDB}" >"${TRINOLI_SVC_DIR}/duckdb-file"
s6-svc -wr "${TRINOLI_SVC_DIR}"
