#!/usr/bin/env bash
set -Eeuo pipefail

URL="https://www.marktstammdatenregister.de/MaStR/Datendownload"

get_download_url() {
    local download_url
    download_url=$(curl -s "$URL" | \
        grep -oE 'https://download\.marktstammdatenregister\.de/Gesamtdatenexport_[0-9]{8}_[0-9]+\.[0-9]+\.zip' | \
        head -n 1)
    echo "$download_url"
}

options() {
    setup REST help:usage -- "Usage: $(basename "$0") [options]..."
    msg -- 'Options:'
    param IF_NEWER_THAN --if-newer-than -- '(input) name of previously downloaded zip file'
    param DOWNLOAD_DIR  --download-dir  -- '(output) directory for download'
    disp  :usage        --help
}

main() {
    eval "$(getoptions options) exit 1"
    local if_newer_than="${IF_NEWER_THAN:-}"
    local download_dir="${DOWNLOAD_DIR:-/mnt/out}"

    local url filename
    url=$(get_download_url)
    filename=$(basename "$url")

    if [[ -z "$if_newer_than" || "$filename" > $(basename "$if_newer_than") ]]
    then
        echo "Downloading $filename to $download_dir"
        mkdir -p "$download_dir"
        axel --num-connections=5 --output="$download_dir/$filename" "$url"
    else
        if_newer_than=$(basename "$if_newer_than")
        echo "$if_newer_than is as recent or more recent than $filename"
    fi
}

main "$@"
