#!/usr/bin/env bash
set -Eeuo pipefail
shopt -s extglob

get_tables() {
    local parquet_dir="$1"

    find "$parquet_dir" -type f -name "*.parquet" -exec basename {} \; | while read -r file; do
        echo "${file%%?(_*).parquet}"
    done | sort -u
}

get_parquet_files() {
    local parquet_dir="$1"
    local table_name="$2"

    find "$parquet_dir" -type f \( -name "${table_name}_*.parquet" -o -name "${table_name}.parquet" \) | sort -V
}

create_table_statement() {
    local db_name="$1"
    local table_name="$2"
    local representative_parquet_file="$3"

    echo "CREATE TABLE $db_name.$table_name AS SELECT * FROM read_parquet('$representative_parquet_file') WITH NO DATA;"
}

add_data_statement() {
    local db_name="$1"
    local table_name="$2"
    local parquet_file="$3"

    echo "CALL ducklake_add_data_files('$db_name', '$table_name', '$parquet_file');"
}

initdb_sql() {
    local db_name="$1"
    local parquet_dir="$2"
    local parquet_dir_override="$3"
    local db_dir="$4"
    local db_file="${db_dir}/catalog.ducklake"
    local data_path="${db_dir}/tmp_always_empty"

    cat <<-.
.bail on
.echo on
LOAD ducklake;
ATTACH 'ducklake:$db_file' AS $db_name (DATA_PATH '$data_path');
.

    local tables
    tables=$(get_tables "$parquet_dir")

    for table in $tables; do
        create_table_statement "$db_name" "$table" "$(get_parquet_files "$parquet_dir" "$table" | head -n1)"
    done

    for table in $tables; do
        get_parquet_files "$parquet_dir" "$table" | while read -r parquet_file; do
            add_data_statement "$db_name" "$table" "$parquet_file"
        done
    done

    echo "DETACH $db_name;"

    if [[ -n parquet_dir_override ]]; then
        cat <<-.
ATTACH '$db_file' AS catalog;
UPDATE catalog.ducklake_data_file
   SET path = replace(path, '$parquet_dir', '$parquet_dir_override')
 WHERE path LIKE '$parquet_dir/%';
DETACH catalog;
.
    fi
}

options() {
    setup REST help:usage -- "Usage: $(basename "$0") [options]..."
    msg -- 'Options:'
    param DB_NAME              --db-name              -- '(input) Database name'
    param PARQUET_DIR          --parquet-dir          -- '(input) Directory containing Parquet files'
    param PARQUET_DIR_OVERRIDE --parquet-dir-override -- '(input) Ducklake data directory override'
    param DB_DIR               --db-dir               -- '(output) DuckDB directory (output is written to $db_dir/catalog.ducklake)'
    disp  :usage               --help
}

main() {
    eval "$(getoptions options) exit 1"
    local db_name="${DB_NAME:-mastr}"
    local parquet_dir="${PARQUET_DIR:-/mnt/parquet}"
    local parquet_dir_override="${PARQUET_DIR_OVERRIDE:-}"
    local db_dir="${DB_DIR:-/mnt/db}"
    local db_dir="${db_dir%/}"

    parquet_dir="${parquet_dir%/}"
    parquet_dir_override="${parquet_dir_override%/}"

    initdb_sql "$db_name" "$parquet_dir" "$parquet_dir_override" "$db_dir" | duckdb
}

main "$@"
