#! /usr/bin/env bash
set -Eeuox pipefail
RUN_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

# Fail early if this file is missing
DUCKDB_FILE=$(<"${RUN_DIR}/duckdb_file")

# Build trinoli
GOPROXY=direct GOBIN="${RUN_DIR}/bin" go install github.com/curiousleo/trinoli@main
TRINOLI_BIN="${RUN_DIR}/bin/trinoli"

# Other setup
BIND_HOST='localhost:8080'
EXTERNAL_HOST='1af6-2a01-4f8-1c1b-a680-00-1.ngrok-free.app'

# TODO: Write readiness notification (perhaps with https://pkg.go.dev/syscall#Write)
# TODO: Consider using s6-envdir for environment variables, including DUCKDB_FILE

exec bwrap \
    --ro-bind "${TRINOLI_BIN}" /opt/trinoli \
    --ro-bind "${DUCKDB_FILE}" /var/duck.db \
    --ro-bind /usr /usr \
    --ro-bind /sys /sys \
    --ro-bind /lib /lib \
    --ro-bind /etc/resolv.conf /etc/resolv.conf \
    --tmpfs /tmp \
    --proc /proc \
    --dev /dev \
    --die-with-parent \
    --dir /run/user/0 \
    --clearenv \
    --setenv DUCKDB_FILE /var/duck.db \
    --setenv BIND_HOST "${BIND_HOST}" \
    --setenv EXTERNAL_HOST "${EXTERNAL_HOST}" \
    --unshare-all \
    --share-net \
    /opt/trinoli \
    2>&1
