-- Common columns (39) across 8 tables, 7 catalog-resolved
CREATE OR REPLACE DICTIONARY KatalogwerteDict
(
    Id UInt64,
    Wert String
)
PRIMARY KEY Id
SOURCE(CLICKHOUSE(TABLE 'Katalogwerte'))
LAYOUT(FLAT())
LIFETIME(0);

CREATE OR REPLACE VIEW Einheiten AS
SELECT 'Biomasse' AS Quelle,
    AltAnlagenbetreiberMastrNummer,
    AnlagenbetreiberMastrNummer,
    AnschlussAnHoechstOderHochSpannung,
    Breitengrad,
    Bruttoleistung,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Bundesland)) AS Bundesland,
    DatumDesBetreiberwechsels,
    DatumEndgueltigeStilllegung,
    DatumLetzteAktualisierung,
    DatumRegistrierungDesBetreiberwechsels,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitBetriebsstatus)) AS EinheitBetriebsstatus,
    EinheitMastrNummer,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitSystemstatus)) AS EinheitSystemstatus,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Einspeisungsart)) AS Einspeisungsart,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Energietraeger)) AS Energietraeger,
    FernsteuerbarkeitNb,
    Gemeinde,
    Gemeindeschluessel,
    GenMastrNummer,
    Hausnummer,
    HausnummerNichtGefunden,
    Hausnummer_nv,
    Inbetriebnahmedatum,
    Kraftwerksnummer_nv,
    Laengengrad,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Land)) AS Land,
    Landkreis,
    LokationMaStRNummer,
    NameStromerzeugungseinheit,
    Nettonennleistung,
    NetzbetreiberpruefungDatum,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(NetzbetreiberpruefungStatus)) AS NetzbetreiberpruefungStatus,
    NichtVorhandenInMigriertenEinheiten,
    Ort,
    Postleitzahl,
    Registrierungsdatum,
    Strasse,
    StrasseNichtGefunden,
    Weic_nv
FROM EinheitenBiomasse
UNION ALL
SELECT 'GeothermieGrubengasDruckentspannung' AS Quelle,
    AltAnlagenbetreiberMastrNummer,
    AnlagenbetreiberMastrNummer,
    AnschlussAnHoechstOderHochSpannung,
    Breitengrad,
    Bruttoleistung,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Bundesland)) AS Bundesland,
    DatumDesBetreiberwechsels,
    DatumEndgueltigeStilllegung,
    DatumLetzteAktualisierung,
    DatumRegistrierungDesBetreiberwechsels,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitBetriebsstatus)) AS EinheitBetriebsstatus,
    EinheitMastrNummer,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitSystemstatus)) AS EinheitSystemstatus,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Einspeisungsart)) AS Einspeisungsart,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Energietraeger)) AS Energietraeger,
    FernsteuerbarkeitNb,
    Gemeinde,
    Gemeindeschluessel,
    GenMastrNummer,
    Hausnummer,
    HausnummerNichtGefunden,
    Hausnummer_nv,
    Inbetriebnahmedatum,
    Kraftwerksnummer_nv,
    Laengengrad,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Land)) AS Land,
    Landkreis,
    LokationMaStRNummer,
    NameStromerzeugungseinheit,
    Nettonennleistung,
    NetzbetreiberpruefungDatum,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(NetzbetreiberpruefungStatus)) AS NetzbetreiberpruefungStatus,
    NichtVorhandenInMigriertenEinheiten,
    Ort,
    Postleitzahl,
    Registrierungsdatum,
    Strasse,
    StrasseNichtGefunden,
    Weic_nv
FROM EinheitenGeothermieGrubengasDruckentspannung
UNION ALL
SELECT 'Kernkraft' AS Quelle,
    AltAnlagenbetreiberMastrNummer,
    AnlagenbetreiberMastrNummer,
    AnschlussAnHoechstOderHochSpannung,
    Breitengrad,
    Bruttoleistung,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Bundesland)) AS Bundesland,
    DatumDesBetreiberwechsels,
    DatumEndgueltigeStilllegung,
    DatumLetzteAktualisierung,
    DatumRegistrierungDesBetreiberwechsels,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitBetriebsstatus)) AS EinheitBetriebsstatus,
    EinheitMastrNummer,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitSystemstatus)) AS EinheitSystemstatus,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Einspeisungsart)) AS Einspeisungsart,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Energietraeger)) AS Energietraeger,
    FernsteuerbarkeitNb,
    Gemeinde,
    Gemeindeschluessel,
    GenMastrNummer,
    Hausnummer,
    HausnummerNichtGefunden,
    Hausnummer_nv,
    Inbetriebnahmedatum,
    Kraftwerksnummer_nv,
    Laengengrad,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Land)) AS Land,
    Landkreis,
    LokationMaStRNummer,
    NameStromerzeugungseinheit,
    Nettonennleistung,
    NetzbetreiberpruefungDatum,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(NetzbetreiberpruefungStatus)) AS NetzbetreiberpruefungStatus,
    NichtVorhandenInMigriertenEinheiten,
    Ort,
    Postleitzahl,
    Registrierungsdatum,
    Strasse,
    StrasseNichtGefunden,
    Weic_nv
FROM EinheitenKernkraft
UNION ALL
SELECT 'Solar' AS Quelle,
    AltAnlagenbetreiberMastrNummer,
    AnlagenbetreiberMastrNummer,
    AnschlussAnHoechstOderHochSpannung,
    Breitengrad,
    Bruttoleistung,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Bundesland)) AS Bundesland,
    DatumDesBetreiberwechsels,
    DatumEndgueltigeStilllegung,
    DatumLetzteAktualisierung,
    DatumRegistrierungDesBetreiberwechsels,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitBetriebsstatus)) AS EinheitBetriebsstatus,
    EinheitMastrNummer,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitSystemstatus)) AS EinheitSystemstatus,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Einspeisungsart)) AS Einspeisungsart,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Energietraeger)) AS Energietraeger,
    FernsteuerbarkeitNb,
    Gemeinde,
    Gemeindeschluessel,
    GenMastrNummer,
    Hausnummer,
    HausnummerNichtGefunden,
    Hausnummer_nv,
    Inbetriebnahmedatum,
    Kraftwerksnummer_nv,
    Laengengrad,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Land)) AS Land,
    Landkreis,
    LokationMaStRNummer,
    NameStromerzeugungseinheit,
    Nettonennleistung,
    NetzbetreiberpruefungDatum,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(NetzbetreiberpruefungStatus)) AS NetzbetreiberpruefungStatus,
    NichtVorhandenInMigriertenEinheiten,
    Ort,
    Postleitzahl,
    Registrierungsdatum,
    Strasse,
    StrasseNichtGefunden,
    Weic_nv
FROM EinheitenSolar
UNION ALL
SELECT 'StromSpeicher' AS Quelle,
    AltAnlagenbetreiberMastrNummer,
    AnlagenbetreiberMastrNummer,
    AnschlussAnHoechstOderHochSpannung,
    Breitengrad,
    Bruttoleistung,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Bundesland)) AS Bundesland,
    DatumDesBetreiberwechsels,
    DatumEndgueltigeStilllegung,
    DatumLetzteAktualisierung,
    DatumRegistrierungDesBetreiberwechsels,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitBetriebsstatus)) AS EinheitBetriebsstatus,
    EinheitMastrNummer,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitSystemstatus)) AS EinheitSystemstatus,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Einspeisungsart)) AS Einspeisungsart,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Energietraeger)) AS Energietraeger,
    FernsteuerbarkeitNb,
    Gemeinde,
    Gemeindeschluessel,
    GenMastrNummer,
    Hausnummer,
    HausnummerNichtGefunden,
    Hausnummer_nv,
    Inbetriebnahmedatum,
    Kraftwerksnummer_nv,
    Laengengrad,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Land)) AS Land,
    Landkreis,
    LokationMaStRNummer,
    NameStromerzeugungseinheit,
    Nettonennleistung,
    NetzbetreiberpruefungDatum,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(NetzbetreiberpruefungStatus)) AS NetzbetreiberpruefungStatus,
    NichtVorhandenInMigriertenEinheiten,
    Ort,
    Postleitzahl,
    Registrierungsdatum,
    Strasse,
    StrasseNichtGefunden,
    Weic_nv
FROM EinheitenStromSpeicher
UNION ALL
SELECT 'Verbrennung' AS Quelle,
    AltAnlagenbetreiberMastrNummer,
    AnlagenbetreiberMastrNummer,
    AnschlussAnHoechstOderHochSpannung,
    Breitengrad,
    Bruttoleistung,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Bundesland)) AS Bundesland,
    DatumDesBetreiberwechsels,
    DatumEndgueltigeStilllegung,
    DatumLetzteAktualisierung,
    DatumRegistrierungDesBetreiberwechsels,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitBetriebsstatus)) AS EinheitBetriebsstatus,
    EinheitMastrNummer,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitSystemstatus)) AS EinheitSystemstatus,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Einspeisungsart)) AS Einspeisungsart,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Energietraeger)) AS Energietraeger,
    FernsteuerbarkeitNb,
    Gemeinde,
    Gemeindeschluessel,
    GenMastrNummer,
    Hausnummer,
    HausnummerNichtGefunden,
    Hausnummer_nv,
    Inbetriebnahmedatum,
    Kraftwerksnummer_nv,
    Laengengrad,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Land)) AS Land,
    Landkreis,
    LokationMaStRNummer,
    NameStromerzeugungseinheit,
    Nettonennleistung,
    NetzbetreiberpruefungDatum,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(NetzbetreiberpruefungStatus)) AS NetzbetreiberpruefungStatus,
    NichtVorhandenInMigriertenEinheiten,
    Ort,
    Postleitzahl,
    Registrierungsdatum,
    Strasse,
    StrasseNichtGefunden,
    Weic_nv
FROM EinheitenVerbrennung
UNION ALL
SELECT 'Wasser' AS Quelle,
    AltAnlagenbetreiberMastrNummer,
    AnlagenbetreiberMastrNummer,
    AnschlussAnHoechstOderHochSpannung,
    Breitengrad,
    Bruttoleistung,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Bundesland)) AS Bundesland,
    DatumDesBetreiberwechsels,
    DatumEndgueltigeStilllegung,
    DatumLetzteAktualisierung,
    DatumRegistrierungDesBetreiberwechsels,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitBetriebsstatus)) AS EinheitBetriebsstatus,
    EinheitMastrNummer,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitSystemstatus)) AS EinheitSystemstatus,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Einspeisungsart)) AS Einspeisungsart,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Energietraeger)) AS Energietraeger,
    FernsteuerbarkeitNb,
    Gemeinde,
    Gemeindeschluessel,
    GenMastrNummer,
    Hausnummer,
    HausnummerNichtGefunden,
    Hausnummer_nv,
    Inbetriebnahmedatum,
    Kraftwerksnummer_nv,
    Laengengrad,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Land)) AS Land,
    Landkreis,
    LokationMaStRNummer,
    NameStromerzeugungseinheit,
    Nettonennleistung,
    NetzbetreiberpruefungDatum,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(NetzbetreiberpruefungStatus)) AS NetzbetreiberpruefungStatus,
    NichtVorhandenInMigriertenEinheiten,
    Ort,
    Postleitzahl,
    Registrierungsdatum,
    Strasse,
    StrasseNichtGefunden,
    Weic_nv
FROM EinheitenWasser
UNION ALL
SELECT 'Wind' AS Quelle,
    AltAnlagenbetreiberMastrNummer,
    AnlagenbetreiberMastrNummer,
    AnschlussAnHoechstOderHochSpannung,
    Breitengrad,
    Bruttoleistung,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Bundesland)) AS Bundesland,
    DatumDesBetreiberwechsels,
    DatumEndgueltigeStilllegung,
    DatumLetzteAktualisierung,
    DatumRegistrierungDesBetreiberwechsels,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitBetriebsstatus)) AS EinheitBetriebsstatus,
    EinheitMastrNummer,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitSystemstatus)) AS EinheitSystemstatus,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Einspeisungsart)) AS Einspeisungsart,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Energietraeger)) AS Energietraeger,
    FernsteuerbarkeitNb,
    Gemeinde,
    Gemeindeschluessel,
    GenMastrNummer,
    Hausnummer,
    HausnummerNichtGefunden,
    Hausnummer_nv,
    Inbetriebnahmedatum,
    Kraftwerksnummer_nv,
    Laengengrad,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(Land)) AS Land,
    Landkreis,
    LokationMaStRNummer,
    NameStromerzeugungseinheit,
    Nettonennleistung,
    NetzbetreiberpruefungDatum,
    dictGet('KatalogwerteDict', 'Wert', toUInt64(NetzbetreiberpruefungStatus)) AS NetzbetreiberpruefungStatus,
    NichtVorhandenInMigriertenEinheiten,
    Ort,
    Postleitzahl,
    Registrierungsdatum,
    Strasse,
    StrasseNichtGefunden,
    Weic_nv
FROM EinheitenWind
;
