-- Common columns (39) across 7 tables, 7 catalog-resolved
CREATE OR REPLACE DICTIONARY mastr.KatalogwerteDict
(
    Id Nullable(UInt64),
    Wert Nullable(String)
)
PRIMARY KEY Id
SOURCE(CLICKHOUSE(TABLE 'Katalogwerte' USER 'mastr' PASSWORD 'mastr'))
LAYOUT(HASHED())
LIFETIME(0);

CREATE OR REPLACE VIEW mastr.Einheiten AS
SELECT 'Biomasse' AS Quelle,
    AltAnlagenbetreiberMastrNummer,
    AnlagenbetreiberMastrNummer,
    AnschlussAnHoechstOderHochSpannung,
    Breitengrad,
    Bruttoleistung,
    IF(Bundesland IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Bundesland))) AS Bundesland,
    DatumDesBetreiberwechsels,
    DatumEndgueltigeStilllegung,
    DatumLetzteAktualisierung,
    DatumRegistrierungDesBetreiberwechsels,
    IF(EinheitBetriebsstatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitBetriebsstatus))) AS EinheitBetriebsstatus,
    EinheitMastrNummer,
    IF(EinheitSystemstatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitSystemstatus))) AS EinheitSystemstatus,
    IF(Einspeisungsart IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Einspeisungsart))) AS Einspeisungsart,
    IF(Energietraeger IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Energietraeger))) AS Energietraeger,
    FernsteuerbarkeitNb,
    Gemeinde,
    Gemeindeschluessel,
    GenMastrNummer,
    Hausnummer,
    HausnummerNichtGefunden,
    Hausnummer_nv,
    Inbetriebnahmedatum,
    Kraftwerksnummer_nv,
    Laengengrad,
    IF(Land IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Land))) AS Land,
    Landkreis,
    LokationMaStRNummer,
    NameStromerzeugungseinheit,
    Nettonennleistung,
    NetzbetreiberpruefungDatum,
    IF(NetzbetreiberpruefungStatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(NetzbetreiberpruefungStatus))) AS NetzbetreiberpruefungStatus,
    NichtVorhandenInMigriertenEinheiten,
    Ort,
    Postleitzahl,
    Registrierungsdatum,
    Strasse,
    StrasseNichtGefunden,
    Weic_nv
FROM EinheitenBiomasse
UNION ALL
SELECT 'GeothermieGrubengasDruckentspannung' AS Quelle,
    AltAnlagenbetreiberMastrNummer,
    AnlagenbetreiberMastrNummer,
    AnschlussAnHoechstOderHochSpannung,
    Breitengrad,
    Bruttoleistung,
    IF(Bundesland IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Bundesland))) AS Bundesland,
    DatumDesBetreiberwechsels,
    DatumEndgueltigeStilllegung,
    DatumLetzteAktualisierung,
    DatumRegistrierungDesBetreiberwechsels,
    IF(EinheitBetriebsstatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitBetriebsstatus))) AS EinheitBetriebsstatus,
    EinheitMastrNummer,
    IF(EinheitSystemstatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitSystemstatus))) AS EinheitSystemstatus,
    IF(Einspeisungsart IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Einspeisungsart))) AS Einspeisungsart,
    IF(Energietraeger IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Energietraeger))) AS Energietraeger,
    FernsteuerbarkeitNb,
    Gemeinde,
    Gemeindeschluessel,
    GenMastrNummer,
    Hausnummer,
    HausnummerNichtGefunden,
    Hausnummer_nv,
    Inbetriebnahmedatum,
    Kraftwerksnummer_nv,
    Laengengrad,
    IF(Land IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Land))) AS Land,
    Landkreis,
    LokationMaStRNummer,
    NameStromerzeugungseinheit,
    Nettonennleistung,
    NetzbetreiberpruefungDatum,
    IF(NetzbetreiberpruefungStatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(NetzbetreiberpruefungStatus))) AS NetzbetreiberpruefungStatus,
    NichtVorhandenInMigriertenEinheiten,
    Ort,
    Postleitzahl,
    Registrierungsdatum,
    Strasse,
    StrasseNichtGefunden,
    Weic_nv
FROM EinheitenGeothermieGrubengasDruckentspannung
UNION ALL
SELECT 'Kernkraft' AS Quelle,
    AltAnlagenbetreiberMastrNummer,
    AnlagenbetreiberMastrNummer,
    AnschlussAnHoechstOderHochSpannung,
    Breitengrad,
    Bruttoleistung,
    IF(Bundesland IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Bundesland))) AS Bundesland,
    DatumDesBetreiberwechsels,
    DatumEndgueltigeStilllegung,
    DatumLetzteAktualisierung,
    DatumRegistrierungDesBetreiberwechsels,
    IF(EinheitBetriebsstatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitBetriebsstatus))) AS EinheitBetriebsstatus,
    EinheitMastrNummer,
    IF(EinheitSystemstatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitSystemstatus))) AS EinheitSystemstatus,
    IF(Einspeisungsart IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Einspeisungsart))) AS Einspeisungsart,
    IF(Energietraeger IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Energietraeger))) AS Energietraeger,
    FernsteuerbarkeitNb,
    Gemeinde,
    Gemeindeschluessel,
    GenMastrNummer,
    Hausnummer,
    HausnummerNichtGefunden,
    Hausnummer_nv,
    Inbetriebnahmedatum,
    Kraftwerksnummer_nv,
    Laengengrad,
    IF(Land IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Land))) AS Land,
    Landkreis,
    LokationMaStRNummer,
    NameStromerzeugungseinheit,
    Nettonennleistung,
    NetzbetreiberpruefungDatum,
    IF(NetzbetreiberpruefungStatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(NetzbetreiberpruefungStatus))) AS NetzbetreiberpruefungStatus,
    NichtVorhandenInMigriertenEinheiten,
    Ort,
    Postleitzahl,
    Registrierungsdatum,
    Strasse,
    StrasseNichtGefunden,
    Weic_nv
FROM EinheitenKernkraft
UNION ALL
SELECT 'Solar' AS Quelle,
    AltAnlagenbetreiberMastrNummer,
    AnlagenbetreiberMastrNummer,
    AnschlussAnHoechstOderHochSpannung,
    Breitengrad,
    Bruttoleistung,
    IF(Bundesland IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Bundesland))) AS Bundesland,
    DatumDesBetreiberwechsels,
    DatumEndgueltigeStilllegung,
    DatumLetzteAktualisierung,
    DatumRegistrierungDesBetreiberwechsels,
    IF(EinheitBetriebsstatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitBetriebsstatus))) AS EinheitBetriebsstatus,
    EinheitMastrNummer,
    IF(EinheitSystemstatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitSystemstatus))) AS EinheitSystemstatus,
    IF(Einspeisungsart IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Einspeisungsart))) AS Einspeisungsart,
    IF(Energietraeger IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Energietraeger))) AS Energietraeger,
    FernsteuerbarkeitNb,
    Gemeinde,
    Gemeindeschluessel,
    GenMastrNummer,
    Hausnummer,
    HausnummerNichtGefunden,
    Hausnummer_nv,
    Inbetriebnahmedatum,
    Kraftwerksnummer_nv,
    Laengengrad,
    IF(Land IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Land))) AS Land,
    Landkreis,
    LokationMaStRNummer,
    NameStromerzeugungseinheit,
    Nettonennleistung,
    NetzbetreiberpruefungDatum,
    IF(NetzbetreiberpruefungStatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(NetzbetreiberpruefungStatus))) AS NetzbetreiberpruefungStatus,
    NichtVorhandenInMigriertenEinheiten,
    Ort,
    Postleitzahl,
    Registrierungsdatum,
    Strasse,
    StrasseNichtGefunden,
    Weic_nv
FROM EinheitenSolar
UNION ALL
SELECT 'Verbrennung' AS Quelle,
    AltAnlagenbetreiberMastrNummer,
    AnlagenbetreiberMastrNummer,
    AnschlussAnHoechstOderHochSpannung,
    Breitengrad,
    Bruttoleistung,
    IF(Bundesland IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Bundesland))) AS Bundesland,
    DatumDesBetreiberwechsels,
    DatumEndgueltigeStilllegung,
    DatumLetzteAktualisierung,
    DatumRegistrierungDesBetreiberwechsels,
    IF(EinheitBetriebsstatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitBetriebsstatus))) AS EinheitBetriebsstatus,
    EinheitMastrNummer,
    IF(EinheitSystemstatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitSystemstatus))) AS EinheitSystemstatus,
    IF(Einspeisungsart IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Einspeisungsart))) AS Einspeisungsart,
    IF(Energietraeger IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Energietraeger))) AS Energietraeger,
    FernsteuerbarkeitNb,
    Gemeinde,
    Gemeindeschluessel,
    GenMastrNummer,
    Hausnummer,
    HausnummerNichtGefunden,
    Hausnummer_nv,
    Inbetriebnahmedatum,
    Kraftwerksnummer_nv,
    Laengengrad,
    IF(Land IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Land))) AS Land,
    Landkreis,
    LokationMaStRNummer,
    NameStromerzeugungseinheit,
    Nettonennleistung,
    NetzbetreiberpruefungDatum,
    IF(NetzbetreiberpruefungStatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(NetzbetreiberpruefungStatus))) AS NetzbetreiberpruefungStatus,
    NichtVorhandenInMigriertenEinheiten,
    Ort,
    Postleitzahl,
    Registrierungsdatum,
    Strasse,
    StrasseNichtGefunden,
    Weic_nv
FROM EinheitenVerbrennung
UNION ALL
SELECT 'Wasser' AS Quelle,
    AltAnlagenbetreiberMastrNummer,
    AnlagenbetreiberMastrNummer,
    AnschlussAnHoechstOderHochSpannung,
    Breitengrad,
    Bruttoleistung,
    IF(Bundesland IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Bundesland))) AS Bundesland,
    DatumDesBetreiberwechsels,
    DatumEndgueltigeStilllegung,
    DatumLetzteAktualisierung,
    DatumRegistrierungDesBetreiberwechsels,
    IF(EinheitBetriebsstatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitBetriebsstatus))) AS EinheitBetriebsstatus,
    EinheitMastrNummer,
    IF(EinheitSystemstatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitSystemstatus))) AS EinheitSystemstatus,
    IF(Einspeisungsart IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Einspeisungsart))) AS Einspeisungsart,
    IF(Energietraeger IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Energietraeger))) AS Energietraeger,
    FernsteuerbarkeitNb,
    Gemeinde,
    Gemeindeschluessel,
    GenMastrNummer,
    Hausnummer,
    HausnummerNichtGefunden,
    Hausnummer_nv,
    Inbetriebnahmedatum,
    Kraftwerksnummer_nv,
    Laengengrad,
    IF(Land IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Land))) AS Land,
    Landkreis,
    LokationMaStRNummer,
    NameStromerzeugungseinheit,
    Nettonennleistung,
    NetzbetreiberpruefungDatum,
    IF(NetzbetreiberpruefungStatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(NetzbetreiberpruefungStatus))) AS NetzbetreiberpruefungStatus,
    NichtVorhandenInMigriertenEinheiten,
    Ort,
    Postleitzahl,
    Registrierungsdatum,
    Strasse,
    StrasseNichtGefunden,
    Weic_nv
FROM EinheitenWasser
UNION ALL
SELECT 'Wind' AS Quelle,
    AltAnlagenbetreiberMastrNummer,
    AnlagenbetreiberMastrNummer,
    AnschlussAnHoechstOderHochSpannung,
    Breitengrad,
    Bruttoleistung,
    IF(Bundesland IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Bundesland))) AS Bundesland,
    DatumDesBetreiberwechsels,
    DatumEndgueltigeStilllegung,
    DatumLetzteAktualisierung,
    DatumRegistrierungDesBetreiberwechsels,
    IF(EinheitBetriebsstatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitBetriebsstatus))) AS EinheitBetriebsstatus,
    EinheitMastrNummer,
    IF(EinheitSystemstatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(EinheitSystemstatus))) AS EinheitSystemstatus,
    IF(Einspeisungsart IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Einspeisungsart))) AS Einspeisungsart,
    IF(Energietraeger IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Energietraeger))) AS Energietraeger,
    FernsteuerbarkeitNb,
    Gemeinde,
    Gemeindeschluessel,
    GenMastrNummer,
    Hausnummer,
    HausnummerNichtGefunden,
    Hausnummer_nv,
    Inbetriebnahmedatum,
    Kraftwerksnummer_nv,
    Laengengrad,
    IF(Land IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(Land))) AS Land,
    Landkreis,
    LokationMaStRNummer,
    NameStromerzeugungseinheit,
    Nettonennleistung,
    NetzbetreiberpruefungDatum,
    IF(NetzbetreiberpruefungStatus IS NULL, NULL, dictGet('KatalogwerteDict', 'Wert', toUInt64(NetzbetreiberpruefungStatus))) AS NetzbetreiberpruefungStatus,
    NichtVorhandenInMigriertenEinheiten,
    Ort,
    Postleitzahl,
    Registrierungsdatum,
    Strasse,
    StrasseNichtGefunden,
    Weic_nv
FROM EinheitenWind
;
